### ISSUE TITLE
/session is being called in the browser context

### ISSUE THREAD

**Issue by ylukem** [toadsapp/toads#9]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1691179/41838225-ae653cb6-7814-11e8-8dbf-4c6884f1ce60.png">

`/session` is being called in the browser context when there already is a valid cookie assigned. This is bad because also the server is creating many new sessions unnecessarily.

The fix for this should be two-fold:

- [ ] Frontend: `/session` shouldn't be called in the browser context
- [ ] Backend: `/session` should check for existence of a valid session cookie, and return/set that same cookies if it's valid.

**Comment by Jarred-Sumner** [comment]
> ![image](https://user-images.githubusercontent.com/709451/41881649-567e6a42-7899-11e8-82c1-0cf4f3f7e9e0.png)

@lukemiles not necessarily true -- if a user's session cookie expires or is deleted after the page has loaded, then it should be called in that case...but you're definitely right that it's being called too frequently.

**Comment by Jarred-Sumner** [comment]
YLukem
